version: '3.3'


services:

  database:
    image: mongo:bionic
    restart: unless-stopped
    volumes:
      - "db-data:/data/db"
    env_file:
      - .database.env
    ports:
      - "27017-27019:27017-27019"
    networks:
      - private-app

  database-admin:
    image: mongo-express:0.54
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "8081:8081"
    env_file:
      - .database-admin.env
    networks:
      - private-app

  backend:
    build: ./
    restart: unless-stopped
    volumes:
      - ./:/app
    env_file:
      - .backend.env
    command: /start-reload.sh
    depends_on:
      - database
    networks:
      - private-app


networks:
  
  private-app:
    driver: bridge


volumes:

  db-data:
    driver: local